


development:
  adapter: postgresql
  database: finalindividual_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: finalindividual_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: finalindividual_production
  pool: 5
  timeout: 5000